# Copyright (c) 2025-present Cesar Saguier Antebi
#
# This file is part of AIGEN Blockchain.
#
# This source code is licensed under the Business Source License 1.1
# found in the LICENSE file in the root directory of this source tree.

[build]
rustflags = [
    "-C", "force-frame-pointers=yes",
    "-C", "relro=full",
    "-C", "stack-protector=strong",
    "-C", "pie",
]

target-dir = "target"

[profile.release]
lto = true
codegen-units = 1
opt-level = 3

[target.x86_64-unknown-linux-gnu]
rustflags = ["-C", "target-cpu=native"]

[target.x86_64-pc-windows-msvc]
rustflags = ["-C", "target-cpu=native"]

[target.x86_64-apple-darwin]
rustflags = ["-C", "target-cpu=native"]
